

script_file_name: npc_strategy.py

# âš™ï¸ Exchange and pair
exchange: binance_perpetual_testnet
trading_pair: ETH-USDT

# ğŸ’° Order config
order_amount: 0.01
order_refresh_time: 15

# ğŸ“ˆ Price source config
price_type: mid

# ğŸ•’ Candle data config
candles_interval: 1m
candles_max_records: 1000
